version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: nursery_db
      POSTGRES_USER: nursery_user
      POSTGRES_PASSWORD: nursery_pass

  web:
    build: ./app
    command: gunicorn nursery_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
    expose:
      - "8000"
    environment:
      DEBUG: 1
      SECRET_KEY: devkey123
      DB_NAME: nursery_db
      DB_USER: nursery_user
      DB_PASSWORD: nursery_pass
      DB_HOST: db
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:


    web:
  ...
  volumes:
    - ./app:/app
    - static_volume:/app/static
