# Generated by Django 5.1.7 on 2025-03-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('supplies', 'Supplies'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
