# Generated by Django 5.1.7 on 2025-04-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_active_teacher_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='relation_to_child',
        ),
        migrations.AddField(
            model_name='parent',
            name='first_name',
            field=models.CharField(default='Unkown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(default='Unkown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
            preserve_default=False,
        ),
    ]
